export const APP_ROUTES = {
  LOGIN: '/auth/login',
  SIGNUP: '/auth/signup',
  FORGOT_PASSWORD: '/auth/forgot-password',
  LANDING_PAGE: '/',
  EXPLORE: '/app/explore',
  PROFILE: '/app/profile',
  ABOUT: '/app/about',
  EVENT_DETAILS: (id: string) => `/app/event/${id}`,
  VERIFY_EMAIL: '/auth/verify-email',
  ADMIN_LOGIN: '/auth/admin',
  VENUE_SECTION: '/app/define-venue-sections',
  MANAGE_EVENT_ROLES: '/app/manage-event-roles',
  RESET_PASSWORD: '/auth/reset-password',
  CREATE_EVENT: '/app/create-event',
  CREATE_EVENT_SUCCESS: '/app/create-event-success',
  MY_EVENTS: '/app/my-events',
  PAYMENT_SETTINGS: '/app/payment-settings',
  ADMIN_DASHBOARD: '/admin',
  ADMIN_EVENTS: '/admin/events',
  ADMIN_EVENT_DETAILS: '/admin/events/:id',
  ADMIN_ORGANIZERS: '/admin/organizers',
};
