export const APP_ROUTES = {
  LOGIN: '/auth/login',
  SIGNUP: '/auth/signup',
  FORGOT_PASSWORD: '/auth/forgot-password',
  VERIFY_EMAIL: '/auth/verify-email',
  RESET_PASSWORD: '/auth/reset-password',
  ADMIN_LOGIN: '/auth/admin',
  ACCEPT_INVITE: '/auth/invitation/accept',
  LANDING_PAGE: '/',
  EXPLORE: '/app/explore',
  PROFILE: '/app/profile',
  PROFILE_PAGE: '/app/profile',
  ABOUT: '/app/about',
  EVENT_DETAILS: (id: string) => `/app/event/${id}`,
  VENUE_SECTION: '/app/define-venue-sections',
  MANAGE_EVENT_ROLES: '/app/manage-event-roles',
  CREATE_EVENT: '/app/create-event',
  EDIT_EVENT: (id: string) => `/app/edit-event/${id}`,
  CREATE_EVENT_SUCCESS: '/app/create-event-success',
  MY_EVENTS: '/app/my-events',
  MY_EVENT: (id: string) => `/app/my-events/${id}`,
  MANAGE_EVENT: (id: string) => `/app/manage-event/${id}`,
  PAYMENT_SETTINGS: '/app/payment-settings',
  EVENT_PAYMENT_SUCCESS: '/app/event-payment-success',
  PAYMENT_SUCCESS: '/app/payment-success',
  ADMIN_DASHBOARD: '/admin',
  EVENT_MANAGEMENT: '/admin/events',
  ADMIN_EVENTS: '/admin/events',
  ADMIN_EVENT_DETAILS: (id: string) => `/admin/events/${id}`,
  ADMIN_ORGANIZERS: '/admin/organizers',
  ADMIN_PROFILE: '/admin/profile',
  ADMIN_EDIT_PROFILE: '/admin/profile',
  ADMIN_SETTINGS: '/admin/settings',
  ADMIN_SETTINGS_SECURITY: '/admin/settings/security',
  ADMIN_SETTINGS_NOTIFICATIONS: '/admin/settings/notifications',
  ADMIN_SETTINGS_TEAM: '/admin/settings/team',
  ADMIN_LOGOUT: '/admin/logout',
} as const;
